"""empty message

Revision ID: 30e96e2d491e
Revises: 
Create Date: 2021-05-11 18:36:36.591843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e96e2d491e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wall_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_name', sa.String(length=150), nullable=True),
    sa.Column('gs', sa.Float(precision=3), nullable=True),
    sa.Column('gb', sa.Float(precision=3), nullable=True),
    sa.Column('phi', sa.Float(precision=3), nullable=True),
    sa.Column('bc', sa.Float(precision=3), nullable=True),
    sa.Column('bb', sa.Float(precision=3), nullable=True),
    sa.Column('bh', sa.Float(precision=3), nullable=True),
    sa.Column('p', sa.Float(precision=3), nullable=True),
    sa.Column('H', sa.Float(precision=3), nullable=True),
    sa.Column('B', sa.Float(precision=3), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_name'),
    sa.UniqueConstraint('design_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wall_design')
    # ### end Alembic commands ###
